[package]
name = "tcp"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
lazy_static = "1.5.0"
log = "0.4.27"
regex = "1.11.1"
tokio = { version = "1.45.1", features = ["full"] }
server_macros = { path = "../server_macros" }
async-trait = "0.1.88"
